### ISSUE TITLE
User can view log in page

### ISSUE THREAD

**Issue by Boyul-Kim** [Boyul-Kim/mastermind#1]
## 💰 Feature

User can view login page

## 🖼 Wireframe

<capture a piece of your figma and drop it here>

![image](https://user-images.githubusercontent.com/35949989/102940136-7aa53d80-4464-11eb-9196-a7b8032ce8e8.png)

## ✅ Tasks

- [x] create DB on pgweb
- [x] insert dummy user to testing login
- [x] create a route in server/index.js to handle POST requests at '/api/login'
- [x] create ClientError class in client-error.js for error middleware
- [x] test the route with HTTPie
- [x] create the skeleton for the login page using React and Bootstrap 4
- [x] insert fonts from font awesome
- [x] log in button should send POST request to server
- [x] if valid log in credentials, should be able to see empty project list page
