### ISSUE TITLE
User can search for specific Task using Search Bar

### ISSUE THREAD

**Issue by Boyul-Kim** [Boyul-Kim/mastermind#10]
## 💰 Feature

User can search for specific Task using Search Bar and do a view swap to only show the specific task

## 🖼 Wireframe

<capture a piece of your figma and drop it here>

![image](https://user-images.githubusercontent.com/35949989/104072707-c83ddc00-51c0-11eb-84a5-e49bca29b3d6.png)

![image](https://user-images.githubusercontent.com/35949989/104072956-5dd96b80-51c1-11eb-98b2-ae8856af0de8.png)

## ✅ Tasks

- [x] create route for to handle GET requests for specific tasks
- [x] test with httpie
- [x] create search bar using bootstrap
- [x] include guards if no tasks match value in search bar
- [x] if value in search bar is clear then default to showing all tasks
