### ISSUE TITLE
User can filter view of Tasks by Status

### ISSUE THREAD

**Issue by Boyul-Kim** [Boyul-Kim/mastermind#11]
## 💰 Feature

User can  filter view of tasks by status. once selected a view swap will occur to only show that specific status and the tasks within it.

## 🖼 Wireframe

<capture a piece of your figma and drop it here>

![image](https://user-images.githubusercontent.com/35949989/103718386-78ba9e80-4f7b-11eb-8b74-c1c729fee6fa.png)

## ✅ Tasks

- [ ] create sql query for filtering
- [ ] create route for handling GET requests for filtering
- [ ] test with httpie
- [ ] create skeleton for filter page
- [ ] style filter page with boostrap4
