### ISSUE TITLE
User can view Project List page

### ISSUE THREAD

**Issue by Boyul-Kim** [Boyul-Kim/mastermind#2]
## 💰 Feature

User can view the Project List page when the user successfully enters in credentials in the login page. This page is the first thing they will see. 

## 🖼 Wireframe

<capture a piece of your figma and drop it here>

![image](https://user-images.githubusercontent.com/35949989/103248419-63ac9280-491f-11eb-9bc9-e339afe5a29e.png)

## ✅ Tasks
- [x] create a route in server/index.js to handle GET requests at '/api/home' 
- [x] create test project data
- [x] test the route with HTTPie
- [x] create the nav bar with side bar icon
- [x] home page should populate each project name into individual cards
- [x] click on a card should route to test page
- [x] change request: use spacing provided from bootstrap instead of my custom css rules
- [x] change request: follow RESTful convention in naming the routes
- [x] change request: Instead of listening for click events, make an anchor tag that triggers a hash change.
- [x] change request: Instead of redirecting, need to have another view to render in App component. Each screen should be chosen by App.
