### ISSUE TITLE
User-can-create-a-new-project

### ISSUE THREAD

**Issue by Boyul-Kim** [Boyul-Kim/mastermind#29]
## 💰 Feature

User can create a project tied to their userId

## 🖼 Wireframe

<capture a piece of your figma and drop it here>

![image](https://user-images.githubusercontent.com/35949989/103835177-6c494b00-503a-11eb-8207-43b5a5cc092c.png)

## ✅ Tasks

- [x] create SQL query to create a new project -> take extra care in making sure that the way the project is falls in line with the other routes in the server
- [x] create route on server to handle POST requests for creating new project
- [x] test with httpie
- [x] create skeleton for create project page
- [x] style with bootstrap
