### ISSUE TITLE
User can select a project

### ISSUE THREAD

**Issue by Boyul-Kim** [Boyul-Kim/mastermind#3]
## 💰 Feature

User can select a project and will show the project page with the Status and the Tasks

## 🖼 Wireframe

<capture a piece of your figma and drop it here>

![image](https://user-images.githubusercontent.com/35949989/102940235-ba6c2500-4464-11eb-87d7-b3bce88549a2.png)

## ✅ Tasks
- [x] create a route in server/index.js to handle GET requests at '/api/projects/:projectId'
- [x] create project dummy data
- [x] test route with HTTPie
- [x] create skeleton for project page
- [x] style using boostrap css classes
- [x] set up hash routing to test page when task is clicked on
- [x] change request: remove code that currently does not have a function (icons, fetch requests, css styling)
- [x] change request: update array title to reflect a name that reflects the purpose of the code more. (details -> tasks)
