### ISSUE TITLE
User can sign up

### ISSUE THREAD

**Issue by Boyul-Kim** [Boyul-Kim/mastermind#32]
## 💰 Feature

User can sign up to get started

## 🖼 Wireframe

<capture a piece of your figma and drop it here>

![image](https://user-images.githubusercontent.com/35949989/104075314-3a192400-51c7-11eb-9c25-df61adf2b76c.png)

![image](https://user-images.githubusercontent.com/35949989/104075507-cfb4b380-51c7-11eb-9f7a-8c35620cd0b9.png)

## ✅ Tasks
- [x] create skeleton for sign up page
- [x] create fetch request for route that handles sign up
- [x] style page with css
- [x] add hash routing to route back to log in page after submit
