### ISSUE TITLE
User can slide horizontally to view all Statuses

### ISSUE THREAD

**Issue by Boyul-Kim** [Boyul-Kim/mastermind#4]
## 💰 Feature

User can slide horizontally to view all Statuses

## 🖼 Wireframe

<capture a piece of your figma and drop it here>

![image](https://user-images.githubusercontent.com/35949989/103397996-7675c180-4aef-11eb-97ee-0ccc4a5c6971.png)

## ✅ Tasks
- [x] create dummy test data for the remaining statuses (For Review, Completed, Backlog)
- [x] modify the route in server/index.js that handles GET requests at '/api/projects/:projectId' to also include the newly created test data
- [x] test route with httpie
- [x] expand on HTML skeleton of page by creating the cards for the remaining statuses (For Review, Completed, Backlog)
- [x] expand on CSS styling for the newly created cards
- [x] using CSS and bootstrap classes create a scrolling function for all status cards when user swipes horizontally
