### ISSUE TITLE
User can create a new Task

### ISSUE THREAD

**Issue by Boyul-Kim** [Boyul-Kim/mastermind#6]
## 💰 Feature

User can create a new Task when the plus button is pressed in the project page status columns

## 🖼 Wireframe

<capture a piece of your figma and drop it here>

![image](https://user-images.githubusercontent.com/35949989/103556532-c42f5880-4e66-11eb-9eee-954910fbb2b7.png)

## ✅ Tasks

- [x] create route on server to handle POST requests to '/api/tasks/create/'
- [x] test route with HTTPie
- [x] add a plus icon to task view page
- [x] add event handler to route to new page and apply it to plus icon
- [x] create new page skeleton on the test page that is already applied to each task in task list
- [x] style page using CSS classes
