### ISSUE TITLE
User can view a task

### ISSUE THREAD

**Issue by Boyul-Kim** [Boyul-Kim/mastermind#7]
## 💰 Feature

User can view a task when they press on the title of the task in the project page

## 🖼 Wireframe

<capture a piece of your figma and drop it here>

![image](https://user-images.githubusercontent.com/35949989/103578570-a6281f00-4e8b-11eb-8fb1-f8b97f621d96.png)

## ✅ Tasks

- [x] create route ('/api/task/view/:taskId') on server to handle GET requests
- [x] test route using httpie
- [x] build out the skeleton of the page
- [x] style the page using bootstrap classes
