### ISSUE TITLE
User can edit a Task

### ISSUE THREAD

**Issue by Boyul-Kim** [Boyul-Kim/mastermind#8]
## 💰 Feature

User can edit a task when they press "Edit' in view task page

## 🖼 Wireframe

<capture a piece of your figma and drop it here>

![image](https://user-images.githubusercontent.com/35949989/103682826-3c1c8200-4f3e-11eb-913b-5d0bf92c9fc4.png)
![image](https://user-images.githubusercontent.com/35949989/103683846-8f430480-4f3f-11eb-9662-c48724bd88ee.png)

## ✅ Tasks

- [x] create route on server to handle update requests
- [x] test on httpie
- [x] create skeleton of page
- [x] style page using css and bootstrap
